stage_1:
  model: da3
  rae:
    target: 
    params:
      encoder_cls: 
      encoder_config_path: 
      encoder_input_size: 
      encoder_params: 
      decoder_config_path: 
      pretrained_decoder_path: 
      noise_tau: 
      reshape_to_2d: 
      normalization_stat_path: 
  da3:
    ckpt: depth-anything/DA3-GIANT-1.1
  vggt:
    ckpt: facebook/VGGT-1B


stage_2:
  model: mvrm
  target: stage2.models.DDT_MVRM_multiview.DiTwDDTHeadMVRM_Multiview
  params:
    # input_size: [27, 36]  # feat_H, feat_W
    input_size: 
    patch_size: 1
    in_channels: 1536
    hidden_size: [1536, 3072]
    depth: [28, 2]
    num_heads: [16, 16]
    mlp_ratio: 4.0
    class_dropout_prob:
    num_classes: 
    use_qknorm: true 
    use_swiglu: true
    use_rope: true
    use_rmsnorm: true
    wo_shift: false
    use_pos_embed: true
  ckpt: 
  # single view ckpt
  # ckpt: result_train/single_view/260202/hypersim-tartanair/TRAIN__fp32__hypersim-tartanair__stage1-da3__stage2-DiTwDDTHeadMVRM__bs-8-accum-1__lr-2e-04__msg-lq-kernel50__global17__no-abs-pos__no-learn-cls/checkpoints/ep-0020000.pt


transport:
  params:
    path_type: 'Linear'
    prediction: 'velocity'
    loss_weight: null
    time_dist_type: 'logit-normal_0_1'


sampler:
  mode: ODE
  params:
    sampling_method: 'euler'
    num_steps: 50
    atol: 1.0e-6
    rtol: 1.0e-3
    reverse: false


guidance:
  method: 'cfg'
  scale: 1.0
  t_min: 0.0
  t_max: 1.0


misc:
  latent_size: [1, 973, 1536] # [v, n+1, d]
  num_classes: 
  time_dist_shift_dim: 1492992  # 1536*27*36
  time_dist_shift_base: 4096


training:
  global_seed: 42
  precision: fp32
  epochs: 10
 
  global_batch_size: 2
  grad_accum_steps: 1
  ema_decay: 0.9995
  num_workers: 0
  shuffle: True
  log_interval: 1


  ckpt_step_interval: 10   # 5k

  vis:
    train_depth_every: 5
    val_depth_every: 5
   

  clip_grad: 1.0
  optimizer:
    lr: 2.0e-4
    betas: [0.9, 0.95]
    weight_decay: 0.0
  scheduler:
    type: linear
    warmup_epochs: 5
    decay_end_epoch: 10
    base_lr: 2e-4
    final_lr: 2e-5
    warmup_from_zero: false
  



log:
  # result_root_dir: result_train/multi_view/260205
  result_root_dir: result_train/multi_view/TMPTMPTMPTMPTMP_FINAL
  tracker:
    name: wandb
    wandb:
      key: e32eed0c2509bf898b850b0065ab62345005fb73
      entity: jinlovespho
      project: eccv26_mv_restoration
      

      # 260203
      # msg: "lq-kernel50__global17__no-abs-pos__no-learn-cls__init-svrm-ckpt"


      # 260205
      # msg: "lqkernel-50__global-17__viewsel-rand-rand"
      # msg: "lqkernel-50__global-17__viewsel-nrand-nrand"
      # msg: "lqkernel-50__global-17__viewsel-ncam-nrand"



      msg: "final"

data:
  train:
    image_size: 512 
    max_num_input_view: 4
    # list: [hypersim,]
    list: [hypersim, tartanair,]
    hypersim:
      ann_path: metadata_images_split_scene_v1.csv
      hq_root_path: /mnt/dataset1/MV_Restoration/hypersim/data
      lq_kernel_size: 50
      view_selection:
        # [random, near_random, near_camera]
        # strategy: random
        # strategy: near_random
        strategy: near_camera
        expand_ratio: 2
    
    tartanair:
      ann_path: 
      hq_root_path: /mnt/dataset1/MV_Restoration/tartanair/data
      lq_kernel_size: 50
      view_selection:
        # [random, near_random]
        # strategy: random
        strategy: near_random 
        expand_ratio: 2
        



  val:
    image_size: 512 
    max_num_input_view: 1
    list: [eth3d]


    eth3d:
      num_eval_img: 3
      eval_scene: [courtyard, delivery_area,  electro,  facade,  kicker,  office,  pipes,  playground,  relief,  relief_2,  terrains]
      ann_path:
      hq_root_path: /mnt/dataset1/MV_Restoration/da3_benchmark_dataset/clean/eth3d
      lq_root_path: /mnt/dataset1/MV_Restoration/da3_benchmark_dataset/cam_blur_300/eth3d
      view_selection:
        strategy: near_random
        expand_ratio: 2

mvrm:

  lq_latent_cond: addition    # [addition, concat]

  train:
    # DPT Head input feats = [19, 27, 33, 39]
    extract_feat_layers: [17]
    concat_feat: False
  val:
    restore_feat_layers: [17]
    concat_feat: False 
    